-- MySQL Script generated by MySQL Workbench
-- Fri Aug 14 10:58:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicación`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publicación` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NULL,
  `imagen` VARCHAR(255) NULL,
  `fecha_publicacion` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_publicacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NULL AUTO_INCREMENT,
  `contenido` TEXT NULL,
  `fecha` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `FK_id_publicacion_idx` (`id_publicacion` ASC),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_comentario_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_comentario_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `mydb`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reacción`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reaccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reaccion` (
  `idReaccion` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NULL,
  `fecha` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  PRIMARY KEY (`idReaccion`),
  INDEX `FK_id_publicacion_idx` (`id_publicacion` ASC),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_reaccion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_reaccion_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `mydb`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `mensaje` TEXT NULL,
  `fecha_envio` DATETIME NULL,
  `id_emisor` INT NOT NULL,
  `id_receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `id_emisor_idx` (`id_emisor` ASC),
  INDEX `id_receptor_idx` (`id_receptor` ASC),
  CONSTRAINT `id_emisor`
    FOREIGN KEY (`id_emisor`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_receptor`
    FOREIGN KEY (`id_receptor`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Amistad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Amistad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Amistad` (
  `idAmistad` INT NOT NULL AUTO_INCREMENT,
  `id_usuario1` INT NOT NULL,
  `id_usuario2` INT NOT NULL,
  `estado` VARCHAR(20) NULL,
  `fecha_solicitud` DATETIME NULL,
  PRIMARY KEY (`idAmistad`),
  INDEX `id_usuario1_idx` (`id_usuario1` ASC),
  INDEX `FK_id_usuario2_idx` (`id_usuario2` ASC),
  CONSTRAINT `FK_id_usuario1`
    FOREIGN KEY (`id_usuario1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_id_usuario2`
    FOREIGN KEY (`id_usuario2`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificación`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `descripcion` VARCHAR(245) NULL,
  `estado` VARCHAR(20) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `FK_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_notificacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
